### ISSUE TITLE
missing Line

### ISSUE THREAD

**Issue by claib** [renevb/simonsays-rpi-pico#2]
import machine
missing in line 10

**Comment by renevb** [comment]
Hi @claib, I think you might be using old code as that sentence doesn't correspond to the correct line number in current code. I just double checked and it worked just fine. Did you pull latest code? Or you can use [raw version](https://raw.githubusercontent.com/renevb/simonsays-rpi-pico/main/simonsays.py) to copy-paste and then save it to your RPi Pico.
